### ISSUE TITLE
Paramatizable rate limiting on server endpoints

### ISSUE THREAD

**Issue by bucko13** [bpanel-org/bpanel#110]
I was thinking about how a faucet application could be made as a plugin on bPanel. The biggest issue is preventing abuse of the endpoint. You could do a naive front end check using local storage, but that’s obviously pretty brittle. A possible long term approach will be to have plugins be added in as middleware. 

One idea I had as a relatively easy, short term solution though that could be pretty useful is to have runtime parameters for the server to turn on rate limiting for specific endpoints. I could see this being useful even when we have backend plugins as a potential security backstop for publicly facing bPanel instances.

**Comment by bucko13** [comment]
@tynes @pinheadmz curious about your thoughts on this?

**Comment by pinheadmz** [comment]
Could make some kind of proof of work? Would that be possible in the front end? Like, then the faucet only sends to addresses that start with `1abc...` or something? I think security middleware will be important too for a bpanel thats publicly a network monitor web page but can be logged in to by the owner to access wallet, etc.

**Comment by bucko13** [comment]
You could probably do something like that on the front end but the problem is you would still need to hook in a check for that in the backend. So still run into the problem that we don't have an exposed plugin/middleware API for backend plugins.

For just network monitoring pages, you'd probably only want to have a node with no wallet anyway. Generally that is my thinking though. The advantage of having the proxy as the communication layer with the nodes in bPanel is the opportunity to add some security backstops (eventually authentication layer too) when the instance is publicly accessible. A node rate limiter could be useful for possible DOS attacks.

**Comment by bucko13** [comment]
Should also probably have some option to disable certain endpoints completely.

**Comment by tynes** [comment]
```js
const endpoints = [
  {
    method: 'POST',
    endpoint: '/foo',
    handler: (req,res) => {},
  }
];

const app = express();
const blacklisted = [];

for (let endpoint of endpoints) {
  if (notBlacklisted(endpoint))
    attach(app, endpoint)
}

function attach(app, endpoint) {
  switch (endpoint.method) {
    case 'POST':
      app.post(endpoint.endpoint, endpoint.handler);
      break;
    case 'USE':
      app.use(endpoint.endpoint, endpoint.handler);
      break;
  }
}
```

**Comment by bucko13** [comment]
Something to consider for this approach to the middleware. I'm not sure how serious it is or difficulties that it could cause, but order obviously matters with server middleware. I had one thought to maybe have an optional parameter for order preference. Not sure if it's necessary or not, but thought I'd throw it in to this thread.
