### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by alvarosilvac** [bpanel-org/bpanel#134]
Receiving this error after running npm start.

I already increased the "--max_old_space_size" and didn't help.

This may be a problem with the new version of Webpack. I heard that there are some memory leaks in other projects after updating to the new version. Found a temporary solution disabling the optimization in the Webpack config.

**Comment by bucko13** [comment]
Yeah I’ve run into this as well and you are correct that it’s a webpack issue. Specifically this seems to be a problem with UglifyJS plugin for webpack. There should be a push up on the development branch that fixes this (at least for dev builds). Hopefully there can be a fix up for webpack to get this fixed, but in the meantime for builds without too many plugins you can still get a decently sized prod bundle of around 5-6MB. 

Thanks for posting about this issue!
