### ISSUE TITLE
Can not use bwallet or simple-wallet 

### ISSUE THREAD

**Issue by show-rosarugosa** [bpanel-org/bpanel#183]
mac os Mojave 10.14.2
node 10.15.0
npm 6.5.0

bcoin run in the docker, I used the command “docker-compose up -d bcoin“  and “npm run start:poll -- --client-id=_docker  ”
use the plugin bwallet

but in the console has this error :
![image](https://user-images.githubusercontent.com/29879298/51724853-410e0100-209a-11e9-9b68-8d5598df2201.png)
![image](https://user-images.githubusercontent.com/29879298/51724871-54b96780-209a-11e9-9fd2-72b4e2621598.png)
![image](https://user-images.githubusercontent.com/29879298/51724884-669b0a80-209a-11e9-8f38-234cee585e41.png)

I used the simple-wallet, but have error too.

**Comment by tynes** [comment]
Try ` @bpanel/bwallet@0.0.7` - I just pushed up a bugfix

**Comment by bucko13** [comment]
Does simple-wallet give you a similar error? Could you also try in incognito mode? There was a fix pushed up around the time when you were having this error to default not to support multisig unless it was explicitly enabled but the old state could still be cached.
