### ISSUE TITLE
NPM version out of date, bug that removes dependencies

### ISSUE THREAD

**Issue by tynes** [bpanel-org/bpanel#23]
Running the command `docker-compose up -d`, there is an error that comes up involving `bcoin` not found. This is a known issue with an out of date version of `npm`

I have confirmed that in the latest build of the base image, `mhart/alpine-node:latest`, `npm` has been updated to version 5.8.0. This fixes the bug involving the removal of dependencies in the `package.json` that are installed via a `git` link

The `bpanel` container needs to be rebuilt and repushed up to Docker hub to fix this bug

**Comment by bucko13** [comment]
You might have an old version of the docker container and need to force a pull? The latest build was 4 days ago: https://hub.docker.com/r/bpanel/bpanel/builds/

**Comment by tynes** [comment]
Good call, pulling `latest` worked
