### ISSUE TITLE
no ARM support for node-sass: must be rebuilt before bpanel install

### ISSUE THREAD

**Issue by pinheadmz** [bpanel-org/bpanel#47]
See: https://github.com/sass/node-sass/issues/1609

Installing bpanel on ARMv6 (Raspberry Pi) this error comes up on start:

```
    ERROR in ./node_modules/css-loader??ref--1-2!./node_modules/postcss-loader/lib??ref--1-3!./node_modules/sass-loader/lib/loader.js??ref--1-4!./webapp/containers/App/app.scss
    Module build failed: Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 8.x
```

This is fixed by stopping bpanel, and executing `npm rebuild node-sass`

**Comment by tynes** [comment]
We should just remove `node-sass` completely

**Comment by bucko13** [comment]
Agreed. Need to make some changes to make sure that the bootstrap grid support still works but will definitely file this as a to do.

**Comment by tynes** [comment]
@bucko13 Where in the codebase is the bootstrap grid stuff happening?

**Comment by bucko13** [comment]
https://github.com/bpanel-org/bpanel/tree/master/webapp/containers/App

**Comment by tynes** [comment]
sass reference has been removed from the project, see #53

**Comment by tynes** [comment]
Merged
