### ISSUE TITLE
Issue when trying to npm install the app

### ISSUE THREAD

**Issue by bigdhri** [bpanel-org/bpanel#55]
Hi, 
   When I try to install the app, I can't get past the bpanel/bcoin-util build, is anyone else encountering this issue?
Thanks,
Dave

**Comment by tynes** [comment]
Can you share your `node` version?
What operating system are you working on?

Can you describe the problem a bit more? I'd be happy to help you get it working

**Comment by bucko13** [comment]
I think this was an issue with the new version of bpanel-utils not being published. Hopefully should be fixed with version 0.0.11 published.

**Comment by bigdhri** [comment]
I agree with bucko13, I think this is because of the latest version not being published. bucko13, when do you think this will be fixed?
Thanks!

**Comment by bigdhri** [comment]
Alright, so  I re-cloned the existing repo, and it looks like the bpanel-utils is fine now, but it fails on bsock. 
Here are the particulars of my system:
1. Node: 8.11.3
2. NPM:  6.2.0
3. OS: Redhat 7
It looks to be a similar issue to the bpanel-utils, only it can't clone the bsock project now.
Any help is appreciated.
Thanks,
Dave
Oh, side note I needed to change the package.json to reference the new version of bpanel-utils: "^0.0.12" to get past the error. If you try to run it with 10 it fails..

**Comment by bucko13** [comment]
Yeah, that issue with the version number I think is related to package-lock sticking to the existing version even if there's a newer one available. I'm kind of wondering if it's worth ditching package-lock for now until the dependencies stabilize a bit more...

Can you share the specific error you're getting with bsock? I haven't run into that installation error before.

**Comment by tynes** [comment]
Could it be the `brq` problem where `body` is undefined and it tries to reference `body.buffer`?

**Comment by tynes** [comment]
@bigdhri - any update? I'd be happy to help you get the application up and running

**Comment by bigdhri** [comment]
I am actually out of town for a week, but when I get back I will try to build this again. Please don’t close this issue yet.

**Comment by tynes** [comment]
@bigdhri ready to help out this week if you need it 👍

**Comment by bigdhri** [comment]
Hey tynes,
   Thanks for the offer, I am going to take you up on it. So I cleaned my environment and started from scratch today. Luckily I was able to get past the issue I encountered before, and download all of the necessary modules to launch the project. I am now working through the docker piece, if I have any issues I will let you know.
Thanks,
Dave

**Comment by bigdhri** [comment]
@tynes Alright, got past the download issue, I can successfully execute npm install. I tried to execute npm start and I received this error: 
 Cannot find module 'bcrypto/lib/bn.js' 
I do have the bcrypto/lib folder, but it does not contain the bn.js, any recommendations to fix the issue?
Thanks,
Dave

**Comment by tynes** [comment]
We just pushed out an updated `bcrypto` version, if you upgrade that should fix the problem

**Comment by bigdhri** [comment]
Thank you @tynes , I was able to refresh everything and I have successfully been able to launch the app.
Thank you for the help!
Dave
