### ISSUE TITLE
Switching Theme Issue

### ISSUE THREAD

**Issue by bigdhri** [bpanel-org/bpanel#72]
Hi,
   I am hoping someone can quickly explain what is happening, I have removed all plugins from the ~/.bpanel/config.js file, and I started the app. I would expect the app to launch with an empty background but it still launches as if it has the genesis-theme. What am I missing?
Thanks

**Comment by bigdhri** [comment]
Thanks @bucko13 that makes sense. So i did figure out what was happening, even though I changed the .bpanel/config.js file, on restart of app it never deletes/updates the index.js file within the webapp/plugins folder. Because of that when the app loads it always had a previous theme. Is the app supposed to update/delete that file?

**Comment by bucko13** [comment]
Yes, that's right. It should reload the index.js file with whatever plugins need to be exposed (in your case it would just be an empty object). It was a very recent update that moved the config file from inside the repo to `config.js` in the home directory so my guess would be that you're still on that version which would still be looking for changes in the old location. Can you confirm the version of bPanel you're running and that your project directory doesn't have a `webapp/plugins/pluginsConfig.js`. If you do have that file, then I would just clone down the most recent version of master from GitHub (or download the zip) and start fresh and you should be good to go. 

And if that's not it... maybe try a fresh copy anyway just so we can see if that changes anything :)

**Comment by tynes** [comment]
@bigdhri anything else that we can help you with?

**Comment by bucko13** [comment]
Closing for now. Feel free to reopen or issue a new bug if something else comes up!
